package pers.elias.financial_management.model;

import java.io.Serializable;
import java.util.List;

public class AccountType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.user_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.account_book_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private Integer accountBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.financial_account_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private Integer financialAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.account_type_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private String accountTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_type
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.id
     *
     * @return the value of account_type.id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.id
     *
     * @param id the value for account_type.id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.user_name
     *
     * @return the value of account_type.user_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.user_name
     *
     * @param userName the value for account_type.user_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.account_book_id
     *
     * @return the value of account_type.account_book_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public Integer getAccountBookId() {
        return accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.account_book_id
     *
     * @param accountBookId the value for account_type.account_book_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public void setAccountBookId(Integer accountBookId) {
        this.accountBookId = accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.financial_account_id
     *
     * @return the value of account_type.financial_account_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public Integer getFinancialAccountId() {
        return financialAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.financial_account_id
     *
     * @param financialAccountId the value for account_type.financial_account_id
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public void setFinancialAccountId(Integer financialAccountId) {
        this.financialAccountId = financialAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.account_type_name
     *
     * @return the value of account_type.account_type_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public String getAccountTypeName() {
        return accountTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.account_type_name
     *
     * @param accountTypeName the value for account_type.account_type_name
     *
     * @mbggenerated Fri Aug 13 16:39:34 CST 2021
     */
    public void setAccountTypeName(String accountTypeName) {
        this.accountTypeName = accountTypeName;
    }

    private Integer limitAccountFinancialId;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public Integer getLimitAccountFinancialId() {
        return limitAccountFinancialId;
    }

    public void setLimitAccountFinancialId(Integer limitAccountFinancialId) {
        this.limitAccountFinancialId = limitAccountFinancialId;
    }

    private List<Integer> limitAccountTypeList;

    public List<Integer> getLimitAccountTypeList() {
        return limitAccountTypeList;
    }

    public void setLimitAccountTypeList(List<Integer> limitAccountTypeList) {
        this.limitAccountTypeList = limitAccountTypeList;
    }

    private List<Integer> accountFinancialIdList;

    public List<Integer> getAccountFinancialIdList() {
        return accountFinancialIdList;
    }

    public void setAccountFinancialIdList(List<Integer> accountFinancialIdList) {
        this.accountFinancialIdList = accountFinancialIdList;
    }

    @Override
    public String toString() {
        return "AccountType{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", accountBookId=" + accountBookId +
                ", financialAccountId=" + financialAccountId +
                ", accountTypeName='" + accountTypeName + '\'' +
                ", limitAccountFinancialId=" + limitAccountFinancialId +
                ", limitAccountTypeList=" + limitAccountTypeList +
                ", accountFinancialIdList=" + accountFinancialIdList +
                '}';
    }
}
