package pers.elias.financial_management.model;

import java.io.Serializable;

public class AccountUserHeader implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user_header.user_name
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user_header.header_path
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    private String headerPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_user_header
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user_header.user_name
     *
     * @return the value of account_user_header.user_name
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user_header.user_name
     *
     * @param userName the value for account_user_header.user_name
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user_header.header_path
     *
     * @return the value of account_user_header.header_path
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    public String getHeaderPath() {
        return headerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user_header.header_path
     *
     * @param headerPath the value for account_user_header.header_path
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    public void setHeaderPath(String headerPath) {
        this.headerPath = headerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user_header
     *
     * @mbggenerated Thu Aug 26 00:12:55 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", headerPath=").append(headerPath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}