package pers.elias.financial_management.model;

import java.io.Serializable;

public class AccountFinancial implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial.id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial.user_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial.account_book_id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    private Integer accountBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_financial.financial_account_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    private String financialAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial.id
     *
     * @return the value of account_financial.id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial.id
     *
     * @param id the value for account_financial.id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial.user_name
     *
     * @return the value of account_financial.user_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial.user_name
     *
     * @param userName the value for account_financial.user_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial.account_book_id
     *
     * @return the value of account_financial.account_book_id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public Integer getAccountBookId() {
        return accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial.account_book_id
     *
     * @param accountBookId the value for account_financial.account_book_id
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public void setAccountBookId(Integer accountBookId) {
        this.accountBookId = accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_financial.financial_account_name
     *
     * @return the value of account_financial.financial_account_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public String getFinancialAccountName() {
        return financialAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_financial.financial_account_name
     *
     * @param financialAccountName the value for account_financial.financial_account_name
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    public void setFinancialAccountName(String financialAccountName) {
        this.financialAccountName = financialAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", accountBookId=").append(accountBookId);
        sb.append(", financialAccountName=").append(financialAccountName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}