package pers.elias.financial_management.model;

import java.io.Serializable;
import java.util.Date;

public class AccountUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_name
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.user_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.second_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String secondPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.roles
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.date_login
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private Date dateLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.date_created
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.tel
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_user.e_mail
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_name
     *
     * @return the value of account_user.user_name
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_name
     *
     * @param userName the value for account_user.user_name
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.user_pass
     *
     * @return the value of account_user.user_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.user_pass
     *
     * @param userPass the value for account_user.user_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.second_pass
     *
     * @return the value of account_user.second_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String getSecondPass() {
        return secondPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.second_pass
     *
     * @param secondPass the value for account_user.second_pass
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setSecondPass(String secondPass) {
        this.secondPass = secondPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.roles
     *
     * @return the value of account_user.roles
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.roles
     *
     * @param roles the value for account_user.roles
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setRoles(String roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.date_login
     *
     * @return the value of account_user.date_login
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public Date getDateLogin() {
        return dateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.date_login
     *
     * @param dateLogin the value for account_user.date_login
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setDateLogin(Date dateLogin) {
        this.dateLogin = dateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.date_created
     *
     * @return the value of account_user.date_created
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.date_created
     *
     * @param dateCreated the value for account_user.date_created
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.tel
     *
     * @return the value of account_user.tel
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.tel
     *
     * @param tel the value for account_user.tel
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_user.e_mail
     *
     * @return the value of account_user.e_mail
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_user.e_mail
     *
     * @param eMail the value for account_user.e_mail
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", userPass=").append(userPass);
        sb.append(", secondPass=").append(secondPass);
        sb.append(", roles=").append(roles);
        sb.append(", dateLogin=").append(dateLogin);
        sb.append(", dateCreated=").append(dateCreated);
        sb.append(", tel=").append(tel);
        sb.append(", eMail=").append(eMail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}