package pers.elias.financial_management.model;

import java.io.Serializable;

public class AccountIndex implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_index.user_name
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_index.account_book_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    private String accountBookIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_index.account_book_init
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    private Integer accountBookInit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_index.account_financial_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    private String accountFinancialIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_index.user_name
     *
     * @return the value of account_index.user_name
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_index.user_name
     *
     * @param userName the value for account_index.user_name
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_index.account_book_index
     *
     * @return the value of account_index.account_book_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public String getAccountBookIndex() {
        return accountBookIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_index.account_book_index
     *
     * @param accountBookIndex the value for account_index.account_book_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public void setAccountBookIndex(String accountBookIndex) {
        this.accountBookIndex = accountBookIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_index.account_book_init
     *
     * @return the value of account_index.account_book_init
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public Integer getAccountBookInit() {
        return accountBookInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_index.account_book_init
     *
     * @param accountBookInit the value for account_index.account_book_init
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public void setAccountBookInit(Integer accountBookInit) {
        this.accountBookInit = accountBookInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_index.account_financial_index
     *
     * @return the value of account_index.account_financial_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public String getAccountFinancialIndex() {
        return accountFinancialIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_index.account_financial_index
     *
     * @param accountFinancialIndex the value for account_index.account_financial_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    public void setAccountFinancialIndex(String accountFinancialIndex) {
        this.accountFinancialIndex = accountFinancialIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_index
     *
     * @mbggenerated Tue Sep 21 03:31:29 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", accountBookIndex=").append(accountBookIndex);
        sb.append(", accountBookInit=").append(accountBookInit);
        sb.append(", accountFinancialIndex=").append(accountFinancialIndex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}