package pers.elias.financial_management.model;

import java.io.Serializable;

public class AccountType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.user_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.account_book_id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    private Integer accountBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.account_type_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    private String accountTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.id
     *
     * @return the value of account_type.id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.id
     *
     * @param id the value for account_type.id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.user_name
     *
     * @return the value of account_type.user_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.user_name
     *
     * @param userName the value for account_type.user_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.account_book_id
     *
     * @return the value of account_type.account_book_id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public Integer getAccountBookId() {
        return accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.account_book_id
     *
     * @param accountBookId the value for account_type.account_book_id
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public void setAccountBookId(Integer accountBookId) {
        this.accountBookId = accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.account_type_name
     *
     * @return the value of account_type.account_type_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public String getAccountTypeName() {
        return accountTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.account_type_name
     *
     * @param accountTypeName the value for account_type.account_type_name
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    public void setAccountTypeName(String accountTypeName) {
        this.accountTypeName = accountTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", accountBookId=").append(accountBookId);
        sb.append(", accountTypeName=").append(accountTypeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}