package pers.elias.financial_management.model;

import java.io.Serializable;

public class AccountBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_book.id
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_book.user_name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_book.name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account_book
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_book.id
     *
     * @return the value of account_book.id
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_book.id
     *
     * @param id the value for account_book.id
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_book.user_name
     *
     * @return the value of account_book.user_name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_book.user_name
     *
     * @param userName the value for account_book.user_name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_book.name
     *
     * @return the value of account_book.name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_book.name
     *
     * @param name the value for account_book.name
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated Mon May 17 01:32:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}