package pers.elias.financial_management.model;

import java.io.Serializable;

public class CategoryFirst implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_first.id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_first.user_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_first.account_book_id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private Integer accountBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_first.in_ex_status
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private String inExStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_first.first_category_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private String firstCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category_first
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_first.id
     *
     * @return the value of category_first.id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_first.id
     *
     * @param id the value for category_first.id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_first.user_name
     *
     * @return the value of category_first.user_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_first.user_name
     *
     * @param userName the value for category_first.user_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_first.account_book_id
     *
     * @return the value of category_first.account_book_id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public Integer getAccountBookId() {
        return accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_first.account_book_id
     *
     * @param accountBookId the value for category_first.account_book_id
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public void setAccountBookId(Integer accountBookId) {
        this.accountBookId = accountBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_first.in_ex_status
     *
     * @return the value of category_first.in_ex_status
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public String getInExStatus() {
        return inExStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_first.in_ex_status
     *
     * @param inExStatus the value for category_first.in_ex_status
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public void setInExStatus(String inExStatus) {
        this.inExStatus = inExStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_first.first_category_name
     *
     * @return the value of category_first.first_category_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public String getFirstCategoryName() {
        return firstCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_first.first_category_name
     *
     * @param firstCategoryName the value for category_first.first_category_name
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    public void setFirstCategoryName(String firstCategoryName) {
        this.firstCategoryName = firstCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_first
     *
     * @mbggenerated Mon May 17 10:32:18 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", accountBookId=").append(accountBookId);
        sb.append(", inExStatus=").append(inExStatus);
        sb.append(", firstCategoryName=").append(firstCategoryName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}