package pers.elias.financial_management.service;

import pers.elias.financial_management.model.AccountType;

import java.util.List;

public interface IAccountTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    int insert(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    int insertSelective(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    AccountType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    int updateByPrimaryKeySelective(AccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_type
     *
     * @mbggenerated Mon Jun 07 19:49:52 CST 2021
     */
    int updateByPrimaryKey(AccountType record);

    /**
     * 查询金融账户
     */
    List<String> selectAccountTypeName(AccountType accountType);

    /**
     * 判断金融账户名称是否存在
     */
    boolean isExists(AccountType accountType);

    /**
     * 查询指定金融账户
     */
    Integer selectIdByAccountType(AccountType accountType);

    /**
     * 通过用户名删除
     */
    int deleteByUserName(String userName);

    /**
     * 通过账本id删除
     */
    int deleteByAccountBookId(Integer accountBookId);
}
