package pers.elias.financial_management.service;

import pers.elias.financial_management.model.AccountCurrentResult;
import pers.elias.financial_management.model.AccountFinancial;
import pers.elias.financial_management.utils.PageBean;

import java.util.List;
import java.util.Map;

public interface IAccountFinancialService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    int insert(AccountFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    int insertSelective(AccountFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    AccountFinancial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    int updateByPrimaryKeySelective(AccountFinancial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_financial
     *
     * @mbggenerated Tue Aug 10 14:08:13 CST 2021
     */
    int updateByPrimaryKey(AccountFinancial record);

    /**
     * 查询金融账户名称
     */
    List<String> selectAll(AccountFinancial accountFinancial);

    /**
     * 查询 id
     */
    Integer selectId(AccountFinancial accountFinancial);

    /**
     * 查询子账户
     */
    List<String> selectSubAccount(Map<String, Object> paramMap);

    /**
     * 查询子账户下的所有流水
     */
    PageBean<AccountCurrentResult> selectSubAccountCurrent(Map<String, Object> paramMap);

    /**
     * 通过用户名删除
     */
    int deleteByUserName(String userName);

    /**
     * 通过账本id删除
     */
    int deleteByAccountBookId(Integer accountBookId);
}
