package pers.elias.financial_management.service;

import pers.elias.financial_management.model.AccountBookHeader;

import java.util.List;
import java.util.Map;

public interface IAccountBookHeaderService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    int insert(AccountBookHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    int insertSelective(AccountBookHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    AccountBookHeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    int updateByPrimaryKeySelective(AccountBookHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book_header
     *
     * @mbggenerated Wed Jul 14 19:11:34 CST 2021
     */
    int updateByPrimaryKey(AccountBookHeader record);

    /**
     * 查询用户信息和路径
     */
    AccountBookHeader selectByAccountBookHeader(AccountBookHeader accountBookHeader);

    /**
     * 判断用户信息和头像路径是否存在
     */
    boolean isExists(AccountBookHeader accountBookHeader);

    /**
     * 更新头像路径
     */
    int updateByAccountBookHeader(AccountBookHeader accountBookHeader);

    /**
     * 通过用户名删除
     */
    int deleteByUserName(String userName);

    /**
     * 通过账本id删除
     */
    int deleteByAccountBookId(Integer accountBookId);

    /**
     * 通过用户名查询
     */
    List<String> selectByUserName(String userName);
}
