package pers.elias.financial_management.service;

import pers.elias.financial_management.model.CategoryTemplate;

import java.util.List;

public interface ICategoryTemplateService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    int insert(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    int insertSelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    CategoryTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    int updateByPrimaryKeySelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 20:12:35 CST 2021
     */
    int updateByPrimaryKey(CategoryTemplate record);

    /**
     * 查询模板
     */
    List<String> selectAllByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 删除模板
     */
    int deleteByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 判断模板是否存在
     */
    boolean isExists(CategoryTemplate categoryTemplate);

    /**
     * 查询指定模板
     */
    CategoryTemplate selectByCategoryTemplate(CategoryTemplate categoryTemplate);
}
