package pers.elias.financial_management.mapper;

import org.springframework.stereotype.Repository;
import pers.elias.financial_management.model.AccountUser;

import java.util.Date;

@Repository
public interface AccountUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    int insert(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    int insertSelective(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    AccountUser selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    int updateByPrimaryKeySelective(AccountUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_user
     *
     * @mbggenerated Tue Sep 14 07:44:41 CST 2021
     */
    int updateByPrimaryKey(AccountUser record);

    /**
     * 查询二级密码
     */
    String selectSecondPass(String userName);

    /**
     * 查询指定用户
     */
    String selectUserName(String userName);

    /**
     * 获取用户的注册日期
     */
    Date selectDateCreated(String userName);
}
