package pers.elias.financial_management.mapper;

import org.springframework.stereotype.Repository;
import pers.elias.financial_management.model.AccountCurrent;
import pers.elias.financial_management.model.AccountCurrentResult;

import java.util.List;
import java.util.Map;

@Repository
public interface AccountCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    int insert(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    int insertSelective(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    AccountCurrent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    int updateByPrimaryKeySelective(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Fri Sep 24 18:49:05 CST 2021
     */
    int updateByPrimaryKey(AccountCurrent record);

    /**
     * 查询月份所有流水
     */
    List<AccountCurrentResult> selectAllByAccountCurrent(Map<String, Object> paramMap);

    /**
     * id 查询
     */
    AccountCurrentResult selectById(Integer id);

    /**
     * 查询总数
     */
    Integer selectCount(Map<String, Object> paramMap);

    /**
     * 查询搜索总数
     */
    Integer selectSearchCount(Map<String, Object> paramMap);

    /**
     * 条件查询
     */
    List<AccountCurrentResult> selectByConditions(Map<String, Object> paramMap);

    /**
     * 查询子账户流水总记录数
     */
    Integer selectSubAccountCount(AccountCurrent accountCurrent);

    /**
     * 通过用户名删除
     */
    int deleteByUserName(String userName);

    /**
     * 通过账本id删除
     */
    int deleteByAccountBookId(Integer accountBookId);

    /**
     * 通过二级分类id删除
     */
    int deleteByCategorySecondId(Integer categorySecondId);

    /**
     * 通过二级金融id删除
     */
    int deleteByAccountTypeId(Integer accountTypeId);

}
