package pers.elias.financial_management.mapper;

import org.springframework.stereotype.Repository;
import pers.elias.financial_management.model.AccountCurrent;
import pers.elias.financial_management.model.AccountCurrentResult;

import java.util.List;

@Repository
public interface AccountCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    int insert(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    int insertSelective(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    AccountCurrent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    int updateByPrimaryKeySelective(AccountCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_current
     *
     * @mbggenerated Mon Jun 21 16:54:00 CST 2021
     */
    int updateByPrimaryKey(AccountCurrent record);

    /**
     * 查询所有流水
     */
    List<AccountCurrentResult> selectAllByAccountCurrent(AccountCurrent accountCurrent);

    /**
     * 条件查询
     */
    List<AccountCurrentResult> selectByConditions(AccountCurrent accountCurrent);
}
