package pers.elias.financial_management.mapper;

import org.springframework.stereotype.Repository;
import pers.elias.financial_management.model.CategoryTemplate;

import java.util.List;

@Repository
public interface CategoryTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int insert(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int insertSelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    CategoryTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int updateByPrimaryKeySelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int updateByPrimaryKey(CategoryTemplate record);

    /**
     * 查询模板
     */
    List<String> selectAllByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 查询指定模板
     */
    CategoryTemplate selectByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 删除模板
     */
    int deleteByCategoryTemplate(CategoryTemplate categoryTemplate);
}
