package pers.elias.financial_management.mapper;

import org.springframework.stereotype.Repository;
import pers.elias.financial_management.model.CategoryTemplate;

import java.util.List;

@Repository
public interface CategoryTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int insert(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int insertSelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    CategoryTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int updateByPrimaryKeySelective(CategoryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_template
     *
     * @mbggenerated Tue Jul 13 22:25:28 CST 2021
     */
    int updateByPrimaryKey(CategoryTemplate record);

    /**
     * 查询模板
     */
    List<String> selectAllByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 查询指定模板
     */
    CategoryTemplate selectByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 查询当前账本下所有收支模板
     */
    List<CategoryTemplate> selectAllTemplate(CategoryTemplate categoryTemplate);

    /**
     * 删除模板
     */
    int deleteByCategoryTemplate(CategoryTemplate categoryTemplate);

    /**
     * 通过用户名删除
     */
    int deleteByUserName(String userName);

    /**
     * 通过账本id删除
     */
    int deleteByAccountBookId(Integer accountBookId);

    /**
     * 通过二级分类id删除
     */
    int deleteByCategorySecondId(Integer categorySecondId);

    /**
     * 通过一级分类id删除
     */
    int deleteByFirstCategoryId(Integer firstCategoryId);

    /**
     * 通过二级金融id删除
     */
    int deleteByAccountTypeId(Integer accountTypeId);
}
