spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/financial_management?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/

    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080






